name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated pull request
          title: My pull request title
          body: My pull request body
          branch: my-new-feature
          base: main

