name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Super-Linter
      uses: github/super-linter@v4
      with:
        # Set the GitHub token secret for the Super-Linter
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Enable all formatting checks for supported languages
        run_all_formatters: true

    - name: Check formatting
      run: |
        if git diff-index --quiet HEAD --; then
          echo "Formatting checks passed!"
        else
          echo "Formatting checks failed. Please run 'make check_format' locally and commit the changes."
          exit 1
        fi
      shell: bash

    - name: Build and test
      run: |
        # Your build and test commands go here
      if: ${{ success() && steps.check_format.outcome == 'success' }}

